"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./app.py']
APP_NAME = "Attendance Nudger"
DATA_FILES = ['config.yml']
OPTIONS = {
        'argv_emulation': True,
        'iconfile': 'icon.svg',
        'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Nudge students via text and email.",
            'CFBundleVersion': "0.1.0",
            'CFBundleShortVersionString': "0.1.0",
            'NSHumanReadableCopyright': u"GNU GPL v3 - https://github.com/JamesVorder/email_nudges"
            }
    }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
